### ISSUE TITLE
Some versions incorrectly marked as 64-bit

### ISSUE THREAD

**Issue by mokesmokes** [FokkeZB/ti-64#9]
e.g. the version Tim noted in this issue https://github.com/mokesmokes/titanium-ios-facebook/issues/20 shows up green, I assume because the Xcode build was for "standard" architectures - but this is not enough. The script should also check if the module was built with >= 3.5.0, otherwise default Xcode settings will give false positives.

**Comment by FokkeZB** [comment]
@ingo is this correct? The release notes tell me that if "xcrun lipo -info" says so it's 64-bit. Does the module indeed also needs to be build using 3.5?

Personally I've been able to build 3.5 apps with 3.4 or even older 64-bit modules.
